# Generated by Django 3.2.10 on 2021-12-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211214_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_detals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=20)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
    ]
